### ISSUE TITLE
Site certificate has expired.

### ISSUE THREAD

**Issue by IvanGoncharov** [18F/discovery#417]

**Comment by brethauer** [comment]
@IvanGoncharov do you mind posting a screenshot?  Seems to be ok for me.. Thank you!!

**Comment by IvanGoncharov** [comment]
@brethauer 

```
$ echo | openssl s_client -connect discovery.18f.us:443 2>/dev/null | openssl x509 -noout -dates
notBefore=Sep 25 00:00:00 2014 GMT
notAfter=Sep 25 23:59:59 2015 GMT
```

You can check it using online tools, for example https://www.sslshopper.com/ssl-checker.html#hostname=https://discovery.18f.us/

**Comment by theresaanna** [comment]
Hi @IvanGoncharov. https://discovery.18f.us is an old instance, for internal use. Do you remember where you found that URL? We should update it. Our production site is at https://discovery.gsa.gov. 

Thanks for letting us know that you ran into this issue.

**Comment by IvanGoncharov** [comment]
> Do you remember where you found that URL?

I got it from Google search results, basically I searched for all pages with SwaggerUI on them.
One of those results was https://discovery.18f.us/

Thanks for explaining issue, I will switch to https://discovery.gsa.gov/

If you interested, here is short description of my project:
My project called "APIs.guru" and it's something like "Wikipedia for REST APIs".
To describe APIs I use most popular format called Swagger(http://swagger.io/).
My API collection is available as Github repo(https://github.com/APIs-guru/api-models) and also through REST API.
Currently it have 140+ APIs(including all Google services) and I also have pool of 1000+ APIs descriptions which I need to process.

Idea is to provide content which will allow 3rd-party services to automatically integrate APIs.
Example of such service could be AnyAPI(https://any-api.com/) portal which visualise all APIs from my collection. Two other integrations are in process: https://sdks.io/ and https://www.corezoid.com/
